name: Build Test

on:
  push:
    branches:
      - "master"
      - "compose"
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  go-lib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.3
          cache-dependency-path: ${{ github.workspace }}/tts-server-lib

      - name: Build tts-server-lib
        run: |
          cd tts-server-lib
          go install golang.org/x/mobile/cmd/gomobile
          gomobile init
          go get golang.org/x/mobile/bind
          gomobile bind -ldflags "-s -w" -v -androidapi=21
          cp -f *.aar $GITHUB_WORKSPACE/app/libs
      - uses: actions/upload-artifact@v3.1.0
        with:
          name: tts-server-lib
          path: tts-server-lib/*.aar

  prepare:
    needs: go-lib
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, 'Merge pull request') }}
    outputs:
      version: ${{ steps.set-ver.outputs.version }}
      versionL: ${{ steps.set-ver.outputs.versionL }}
      lanzou: ${{ steps.check.outputs.lanzou }}
    steps:
      - id: set-ver
        run: |
          echo "version=$(date -d "8 hour" -u +3.%y.%m%d%H)" >> $GITHUB_OUTPUT
          echo "versionL=$(date -d "8 hour" -u +3.%y.%m%d%H%M)" >> $GITHUB_OUTPUT
      - id: check
        run: |
          if [ ${{ secrets.LANZOU_ID }} ]; then
            echo "lanzou=yes" >> $GITHUB_OUTPUT
          fi

  build:
    needs: prepare
    strategy:
      matrix:
        product: [ { name: "App原版", value: app }, { name: "Dev共存版", value: dev} ]

      fail-fast: false
    runs-on: ubuntu-latest
    env:
      product: ${{ matrix.product.value }}
      product_name: ${{ matrix.product.value }}
      VERSION: ${{ needs.prepare.outputs.version }}
      VERSIONL: ${{ needs.prepare.outputs.versionL }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v3
        with:
          name: tts-server-lib
          path: ${{ github.workspace }}/app/libs

      -  uses: actions/setup-java@v3
         with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Release Apk Sign
        run: |
          echo "给apk增加签名"
          # not use this output
          # echo "KeyStore=yes" >> $GITHUB_OUTPUT
          echo RELEASE_KEY_ALIAS='${{ secrets.RELEASE_KEY_ALIAS }}' >> local.properties
          echo RELEASE_KEY_PASSWORD='${{ secrets.RELEASE_KEY_PASSWORD }}' >> local.properties
          echo RELEASE_STORE_PASSWORD='${{ secrets.RELEASE_STORE_PASSWORD }}' >> local.properties
          echo RELEASE_STORE_FILE='./key.jks' >> local.properties
          echo ${{ secrets.RELEASE_KEY_STORE }} | base64 --decode > $GITHUB_WORKSPACE/app/key.jks



      - name: Build With Gradle
        run: |
          echo "开始${{ env.product }}$typeName构建"
          chmod +x gradlew
          ./gradlew assemble${{ env.product }}release --build-cache --parallel --daemon --warning-mode all
         
      - name: Upload App To Artifact
        uses: actions/upload-artifact@v3
        with:
          name: TTS-Server.${{ env.product }}.${{ env.type }}
          path: ${{ github.workspace }}/apk/*.apk

  lanzou:
    needs: [ prepare, build ]
    if: ${{ github.event_name != 'pull_request' && needs.prepare.outputs.lanzou == 'yes' }}
    runs-on: ubuntu-latest
    env:
      # 登录蓝奏云后在控制台运行document.cookie
      ylogin: ${{ secrets.LANZOU_ID }}
      phpdisk_info: ${{ secrets.LANZOU_PSD }}
      # 蓝奏云里的文件夹ID
      LANZOU_FOLDER_ID: '9494606'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          path: apk/
      - working-directory: apk/
        run: mv */*.apk . ;rm -rf */
      - name: Upload To Lanzou
        continue-on-error: true
        run: |
          path="$GITHUB_WORKSPACE/apk/"
          python3 $GITHUB_WORKSPACE/.github/scripts/lzy_web.py "$path" "$LANZOU_FOLDER_ID"
          echo "[$(date -u -d '+8 hour' '+%Y.%m.%d %H:%M:%S')] 分享链接: https://miaogongzi.lanzout.com/b01rvtuhg"

 
